name: snowflake_dbt_tests
version: 1.0.0
config-version: 2

profile: snowflake_dbt_tests

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  snowflake_dbt_tests:
    +materialized: view
    staging:
      +schema: staging
      +tags: ["staging"]
    marts:
      +schema: marts
      +materialized: table
      +tags: ["mart"]

seeds:
  snowflake_dbt_tests:
    +schema: staging
